### PR TITLE
Update Translation

### PR DESCRIPTION
**Pull request by SoraKohaku**
Fixed Some Old Kanji to Kanji General

### CODE REVIEW

**Comment by rkarpuzov** [comment]
Some strings in English must be fixed, so soon will have new merge
Thanks to Nur1Labs!!!

**Comment by SoraKohaku** [comment]
no problem. so need fixed is english?i think the kanji need fix
ahahhaa...if some mistake tell here maybe some string can fixed. particular
same of it. similar but different spell.

**Comment by rkarpuzov** [comment]
No, you have translated string in source tags, which will make the translation useless. Translation between <transation></translation> tags must be translated. 211 lines are affected:
https://pastebin.com/p5Rj772p

**Comment by SoraKohaku** [comment]
ah so that it...cuz not understand what .ts work

On Dec 22, 2017 3:49 PM, "rkarpuzov" <notifications@github.com> wrote:

No, you have translated string in source tags, which will make the
translation useless. Translation between tags must be translated. 211 lines
are affected:
14c14
< &Choose

    <source>C&amp;hoose</source>

17,18c17,18
< These are your Aurum addresses for sending payments. Always check the
amount and the receiving address before sending coins.
< These are your Aurum addresses for receiving payments. It is recommended
to use a new receiving address for each transaction.

    <source>These are your Bitcoin addresses for sending payments.
Always check the amount and the receiving address before sending
coins.</source>
    <source>These are your Bitcoin addresses for receiving payments.
It is recommended to use a new receiving address for each
transaction.</source>

39c39
< Warning: If you encrypt your wallet and lose your passphrase, you will
<b>LOSE ALL OF YOUR AURUM</b>!

    <source>Warning: If you encrypt your wallet and lose your
passphrase, you will &lt;b&gt;LOSE ALL OF YOUR
BITCOINS&lt;/b&gt;!</source>

41c41
< Aurum Core will close now to finish the encryption process. Remember that
encrypting your wallet cannot fully protect your bitcoins from being stolen
by malware infecting your computer.

    <source>Bitcoin Core will close now to finish the encryption
process. Remember that encrypting your wallet cannot fully protect
your bitcoins from being stolen by malware infecting your
computer.</source>

63c63
< &Exit

    <source>E&amp;xit</source>

74c74
< Aurum Core client

    <source>Bitcoin Core client</source>

77c77
< Send coins to a Aurum address

    <source>Send coins to a Bitcoin address</source>

83c83
< Aurum

    <source>Bitcoin</source>

87c87
< Show information about Aurum Core

    <source>Show information about Bitcoin Core</source>

91,92c91,92
< Sign messages with your Aurum addresses to prove you own them
< Verify messages to ensure they were signed with specified Aurum addresses

    <source>Sign messages with your Bitcoin addresses to prove you own
them</source>
    <source>Verify messages to ensure they were signed with specified
Bitcoin addresses</source>

97,100c97,100
< Aurum Core
< Request payments (generates QR codes and aurum: URIs)
< &About Aurum Core
< Modify configuration options for Aurum Core

    <source>Bitcoin Core</source>
    <source>Request payments (generates QR codes and bitcoin: URIs)</source>
    <source>&amp;About Bitcoin Core</source>
    <source>Modify configuration options for Bitcoin Core</source>

103c103
< Open a aurum: URI or payment request

    <source>Open a bitcoin: URI or payment request</source>

105,106c105,106
< Show the Aurum Core help message to get a list with possible Bitcoin
command-line options
< %n active connection(s) to Aurum network

    <source>Show the Bitcoin Core help message to get a list with
possible Bitcoin command-line options</source>
    <source>%n active connection(s) to Bitcoin network</source>

210c210
< Aurum Core

    <source>Bitcoin Core</source>

225,227c225,227
< Welcome to Aurum Core.
< As this is the first time the program is launched, you can choose where
Aurum Core will store its data.
< Bitcoin Core will download and store a copy of the Aurum block chain. At
least %1GB of data will be stored in this directory, and it will grow over
time. The wallet will also be stored in this directory.

    <source>Welcome to Bitcoin Core.</source>
    <source>As this is the first time the program is launched, you can
choose where Bitcoin Core will store its data.</source>
    <source>Bitcoin Core will download and store a copy of the Bitcoin
block chain. At least %1GB of data will be stored in this directory,
and it will grow over time. The wallet will also be stored in this
directory.</source>

230c230
< Aurum Core

    <source>Bitcoin Core</source>

249c249
< The user interface language can be set here. This setting will take
effect after restarting Aurum Core.

    <source>The user interface language can be set here. This setting
will take effect after restarting Bitcoin Core.</source>

256,257c256,257
< Automatically start Aurum Core after logging in to the system.
< &Start Aurum Core on system login

    <source>Automatically start Bitcoin Core after logging in to the
system.</source>
    <source>&amp;Start Bitcoin Core on system login</source>

264c264
< Automatically open the Aurum client port on the router. This only works
when your router supports UPnP and it is enabled.

    <source>Automatically open the Bitcoin client port on the router.
This only works when your router supports UPnP and it is
enabled.</source>

266c266
< Connect to the Aurum network through a SOCKS5 proxy.

    <source>Connect to the Bitcoin network through a SOCKS5 proxy.</source>

276c276
< Connect to the Aurum network through a separate SOCKS5 proxy for Tor
hidden services.

    <source>Connect to the Bitcoin network through a separate SOCKS5
proxy for Tor hidden services.</source>

297c297
< The displayed information may be out of date. Your wallet automatically
synchronizes with the Aurum network after a connection is established, but
this process has not completed yet.

    <source>The displayed information may be out of date. Your wallet
automatically synchronizes with the Bitcoin network after a connection
is established, but this process has not completed yet.</source>

321c321
< Cannot start aurum: click-to-pay handler

    <source>Cannot start bitcoin: click-to-pay handler</source>

323c323
< URI cannot be parsed! This can be caused by an invalid Aurum address or
malformed URI parameters.

    <source>URI cannot be parsed! This can be caused by an invalid
Bitcoin address or malformed URI parameters.</source>

340c340
< Enter a Aurum address (e.g. %1)

    <source>Enter a Bitcoin address (e.g. %1)</source>

369c369
< Open the Aurum Core debug log file from the current data directory. This
can take a few seconds for large log files.

    <source>Open the Bitcoin Core debug log file from the current data
directory. This can take a few seconds for large log files.</source>

409c409
< Welcome to the Aurum Core RPC console.

    <source>Welcome to the Bitcoin Core RPC console.</source>

482c482
< If the custom fee is set to 1000 aurtoshi and the transaction is only 250
bytes, then "per kilobyte" only pays 250 aurtoshi in fee, while "total at
least" pays 1000 satoshis. For transactions bigger than a kilobyte both pay
by kilobyte.

    <source>If the custom fee is set to 1000 satoshis and the
transaction is only 250 bytes, then "per kilobyte" only pays 250
satoshis in fee, while "total at least" pays 1000 satoshis. For
transactions bigger than a kilobyte both pay by kilobyte.</source>

525c525
< Warning: Invalid Aurum address

    <source>Warning: Invalid Bitcoin address</source>

537c537
< The Aurum address to send the payment to

    <source>The Bitcoin address to send the payment to</source>

542c542
< The fee will be deducted from the amount being sent. The recipient will
receive less aurum than you enter in the amount field. If multiple
recipients are selected, the fee is split equally.

    <source>The fee will be deducted from the amount being sent. The
recipient will receive less bitcoins than you enter in the amount
field. If multiple recipients are selected, the fee is split
equally.</source>

551c551
< Aurum Core is shutting down...

    <source>Bitcoin Core is shutting down...</source>

555,556c555,556
< You can sign messages/agreements with your addresses to prove you can
receive aurums sent to them. Be careful not to sign anything vague or
random, as phishing attacks may try to trick you into signing your identity
over to them. Only sign fully-detailed statements you agree to.
< The Aurum address to sign the message with

    <source>You can sign messages/agreements with your addresses to
prove you can receive bitcoins sent to them. Be careful not to sign
anything vague or random, as phishing attacks may try to trick you
into signing your identity over to them. Only sign fully-detailed
statements you agree to.</source>
    <source>The Bitcoin address to sign the message with</source>

564c564
< Sign the message to prove you own this Aurum address

    <source>Sign the message to prove you own this Bitcoin address</source>

570,571c570,571
< The Aurum address the message was signed with
< Verify the message to ensure it was signed with the specified Aurum
address

    <source>The Bitcoin address the message was signed with</source>
    <source>Verify the message to ensure it was signed with the
specified Bitcoin address</source>

587,588c587,588
< Aurum Core
< The Aurum Core developers

    <source>Bitcoin Core</source>
    <source>The Bitcoin Core developers</source>

710c710
< Please check that your computer's date and time are correct! If your
clock is wrong Aurum Core will not work properly.

    <source>Please check that your computer's date and time are
correct! If your clock is wrong Bitcoin Core will not work
properly.</source>

712d711
< Prune: last wallet synchronisation goes beyond pruned data. You need to
-reindex (download the whole blockchain again in case of pruned node)
714d712
< Rescans are not possible in pruned mode. You will need to use -reindex
which will download the whole blockchain again.
724c722
< MITソフトウェアライセンスのもとで配布されています。付属のCOPYINGファイルまたは<http://www.
opensource.org/licenses/mit-license.php&gt;を参照してください。

    <translation>Veröffentlicht unter der MIT-Softwarelizenz, siehe
beiligende Datei COPYING oder
&lt;http://www.opensource.org/licenses/mit-license.php&gt;.</translation>

727d724
< The block database contains a block which appears to be from the future.
This may be due to your computer's date and time being set incorrectly.
Only rebuild the block database if you are sure that your computer's date
and time are correct
759d755
< Keep the transaction memory pool below <n> megabytes (default: %u)
781c777
< Cannot obtain a lock on data directory %s. Aurum Core is probably already
running.

    <source>Cannot obtain a lock on data directory %s. Bitcoin Core is
probably already running.</source>

801d796
< Always relay transactions received from whitelisted peers (default: %d)
806,807c801,802
< Copyright (C) 2009-%i The Aurum Core Developers
< Error loading wallet.dat: Wallet requires newer version of Aurum Core

    <source>Copyright (C) 2009-%i The Bitcoin Core Developers</source>
    <source>Error loading wallet.dat: Wallet requires newer version of
Bitcoin Core</source>

811c806
< Initialization sanity check failed. Aurum Core is shutting down.

    <source>Initialization sanity check failed. Bitcoin Core is
shutting down.</source>

823d817
< Reducing -maxconnections from %d to %d, because of system limitations.
841c835
< Wallet needed to be rewritten: restart Aurum Core to complete

    <source>Wallet needed to be rewritten: restart Bitcoin Core to
complete</source>

863,864d856
< Support filtering of blocks and transaction with bloom filters (default:
%u)
< Total length of network version string (%i) exceeds maximum length (%i).
Reduce the number or size of uacomments.
868d859
< Username and hashed password for JSON-RPC connections. The field <userpw>
comes in the format: <USERNAME>:<SALT>$<HASH>. A canonical python script is
included in share/rpcuser. This option can be specified multiple times

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rkarpuzov/Aurumcoin-0.12/pull/1#issuecomment-353534127>,
or mute the thread

**Pull request merged**
